name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # bump server version in /server/package.json
      - name: Bump server version
        id: version
        run: |
          cd server
          pnpm version prerelease --preid=beta
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_ENV
          cd ..
      
      # commit the version bump
      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add server/package.json server/package-lock.json || true
          git commit -m "chore: bump server version to ${{ env.version }}" || echo "No changes to commit"
          git push

      - name: Install dependencies
        run: pnpm install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # k1b1b0t/achievibit-v3:latest and one for the version
          tags: |
            k1b1b0t/achievibit-v3:latest
            k1b1b0t/achievibit-v3:${{ env.version }}
